import { createFileRoute } from "@tanstack/react-router";
import { PublicPageLayout } from "@/components/PublicPageLayout";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — CareCircle" },
      {
        name: "description",
        content: "Privacy Policy for CareCircle. Learn how we handle your data.",
      },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <PublicPageLayout title="Privacy Policy" description="Effective date: August 21, 2026">
      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-foreground">
        <section>
          <h2 className="text-xl font-semibold mb-3">1. Introduction</h2>
          <p className="text-muted-foreground leading-relaxed">
            CareCircle ("we," "our," or "us") is an AI-powered care companion application that helps
            families coordinate care for their elderly loved ones. This Privacy Policy explains how
            we collect, use, store, and protect your personal information when you use our
            application and services.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            By using CareCircle, you agree to the practices described in this Privacy Policy. If you
            do not agree, please do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">2. Information We Collect</h2>

          <h3 className="text-lg font-medium mt-4 mb-2">Account Information</h3>
          <p className="text-muted-foreground leading-relaxed">
            When you create an account, we collect your email address, name, and password (stored in
            encrypted form). You may also optionally provide a date of birth and profile picture.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">User Profile Information</h3>
          <p className="text-muted-foreground leading-relaxed">
            You may choose to enter a user profile including a name, age, date of birth, and profile
            picture. This information is used to personalize your experience within the application.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">AI Conversations</h3>
          <p className="text-muted-foreground leading-relaxed">
            CareCircle provides AI-powered conversational check-ins. We store your conversation
            history to maintain context across sessions and to provide a coherent experience. These
            conversations are processed by OpenRouter, a third-party AI API provider, to generate
            responses. Your messages, the AI's responses, and conversation metadata are stored in
            our database.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">AI-Generated Responses</h3>
          <p className="text-muted-foreground leading-relaxed">
            AI-generated responses are produced by third-party language models accessed through
            OpenRouter. These responses are not medical advice. We store generated responses as part
            of your conversation history.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">Persistent AI Memory</h3>
          <p className="text-muted-foreground leading-relaxed">
            CareCircle extracts and stores certain durable information from your conversations (such
            as your name, preferences, family relationships, and routines) to improve the
            personalization of future interactions. This memory data is stored in our database and
            associated with your account. You can view, manage, and delete your stored memories at
            any time from your profile page.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">Daily Check-Ins</h3>
          <p className="text-muted-foreground leading-relaxed">
            Daily check-in responses, mood scores, and summaries generated by the AI are stored in
            our database to track wellbeing over time.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">Medication Information</h3>
          <p className="text-muted-foreground leading-relaxed">
            If you use the medication tracking feature, we store information about medications you
            enter, including medication names, dosages, frequencies, and reminder settings.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">Appointment Information</h3>
          <p className="text-muted-foreground leading-relaxed">
            If you use the appointment management feature, we store appointment details you enter,
            including dates, times, descriptions, and reminder settings.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">Family and Caregiver Information</h3>
          <p className="text-muted-foreground leading-relaxed">
            CareCircle supports family and caregiver coordination. If you invite family members or
            caregivers, we store their contact information and role assignments to enable care
            coordination features.
          </p>

          <h3 className="text-lg font-medium mt-4 mb-2">Subscription and Billing Information</h3>
          <p className="text-muted-foreground leading-relaxed">
            We use Paddle as our payment processor. When you subscribe to CareCircleAI Pro, Paddle
            collects and processes your payment information. We do not store your credit card number
            or full payment details on our servers. We store your Paddle customer ID and
            subscription status to manage your access level.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">3. How We Use Your Information</h2>
          <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-2">
            <li>To provide and maintain the CareCircle service</li>
            <li>To personalize your AI companion experience</li>
            <li>To track medication and appointment schedules</li>
            <li>To enable family and caregiver coordination</li>
            <li>To process subscriptions and payments</li>
            <li>To improve our service and develop new features</li>
            <li>To send important service notifications (e.g., medication reminders)</li>
            <li>To detect and prevent fraud or abuse</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">4. Data Storage and Security</h2>
          <p className="text-muted-foreground leading-relaxed">
            Your data is stored in Supabase, a hosted PostgreSQL database platform. Supabase
            provides encryption at rest and in transit. We implement row-level security policies to
            ensure that your data is only accessible by your account.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            We take reasonable measures to protect your personal information, but no method of
            electronic transmission or storage is completely secure. We cannot guarantee absolute
            security.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">5. Third-Party Services</h2>
          <p className="text-muted-foreground leading-relaxed">
            We use the following third-party services to operate CareCircle:
          </p>
          <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-2">
            <li>
              <strong>Supabase</strong> — Authentication, database hosting, and real-time
              subscriptions. Supabase's privacy policy applies to data processed by their platform.
            </li>
            <li>
              <strong>OpenRouter</strong> — AI API provider that processes your conversation
              messages and generates AI responses. Your messages are sent to OpenRouter when you
              interact with the AI companion. OpenRouter forwards requests to underlying model
              providers (such as Google) to generate responses.
            </li>
            <li>
              <strong>Paddle</strong> — Payment processing for subscriptions. Paddle processes your
              payment information directly. We do not have access to your full payment details.
            </li>
            <li>
              <strong>Cloudflare</strong> — Application hosting and delivery.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">6. Data Retention</h2>
          <p className="text-muted-foreground leading-relaxed">
            We retain your data for as long as your account is active or as needed to provide the
            service. When you delete your account, we will delete or anonymize your personal data
            within a reasonable timeframe, except where we are required to retain certain
            information for legal or legitimate business purposes.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Conversation history, memories, medication data, and appointment data are retained while
            your account is active and deleted when you close your account.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">7. Cookies and Local Storage</h2>
          <p className="text-muted-foreground leading-relaxed">
            CareCircle uses the following storage mechanisms:
          </p>
          <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-2">
            <li>
              <strong>Local Storage</strong> — Used to persist your authentication session and theme
              preferences. This data stays on your device and is not sent to any third party.
            </li>
            <li>
              <strong>Cookies</strong> — A single cookie is used to remember your sidebar UI
              preference (open/closed). This is a purely functional cookie with no tracking purpose.
            </li>
          </ul>
          <p className="text-muted-foreground leading-relaxed">
            We do not use tracking cookies, advertising cookies, or any analytics cookies.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">8. Analytics</h2>
          <p className="text-muted-foreground leading-relaxed">
            CareCircle does not use any third-party analytics or tracking services. We do not use
            Google Analytics, Mixpanel, Segment, or similar tracking tools.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">9. Your Rights</h2>
          <p className="text-muted-foreground leading-relaxed">You have the right to:</p>
          <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-2">
            <li>Access the personal data we hold about you</li>
            <li>Correct inaccurate personal data</li>
            <li>Delete your account and associated data</li>
            <li>Export your data in a portable format</li>
            <li>Manage and delete your stored AI memories</li>
            <li>Object to or restrict certain processing of your data</li>
          </ul>
          <p className="text-muted-foreground leading-relaxed">
            To exercise any of these rights, please contact us using the information on our{" "}
            <a href="/contact" className="text-primary underline">
              Contact page
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">10. Account Deletion</h2>
          <p className="text-muted-foreground leading-relaxed">
            You may delete your account at any time from your profile page. Upon deletion, all of
            your personal data, conversation history, memories, medication records, and appointment
            data will be permanently removed from our systems.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">11. Children's Privacy</h2>
          <p className="text-muted-foreground leading-relaxed">
            CareCircle is not intended for use by children under 13 years of age. We do not
            knowingly collect personal information from children under 13.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">12. Changes to This Privacy Policy</h2>
          <p className="text-muted-foreground leading-relaxed">
            We may update this Privacy Policy from time to time. We will notify you of any material
            changes by posting the new Privacy Policy on this page and updating the effective date.
            We encourage you to review this Privacy Policy periodically.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">13. Contact Us</h2>
          <p className="text-muted-foreground leading-relaxed">
            If you have any questions about this Privacy Policy, please visit our{" "}
            <a href="/contact" className="text-primary underline">
              Contact page
            </a>{" "}
            or reach out to us at help.carecircle@gmail.com.
          </p>
        </section>
      </div>
    </PublicPageLayout>
  );
}
